/* THIS FILE IS AUTOGENERATED BY "npm run gen", DON'T TOUCH IT! */

import React from 'react';

import CardBuilder
  from '../../packages/cf-builder-card/example/basic/component';
import highlightedCardBuilder
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-builder-card/example/basic/component';
import PaginationBuilder
  from '../../packages/cf-builder-pagination/example/basic/component';
import highlightedPaginationBuilder
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-builder-pagination/example/basic/component';
import TableBuilder
  from '../../packages/cf-builder-table/example/basic/component';
import highlightedTableBuilder
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-builder-table/example/basic/component';
import ButtonComponent
  from '../../packages/cf-component-button/example/basic/component';
import highlightedButtonComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-button/example/basic/component';
import CalloutComponent
  from '../../packages/cf-component-callout/example/basic/component';
import highlightedCalloutComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-callout/example/basic/component';
import CardComponent
  from '../../packages/cf-component-card/example/basic/component';
import highlightedCardComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-card/example/basic/component';
import CheckboxComponent
  from '../../packages/cf-component-checkbox/example/basic/component';
import highlightedCheckboxComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-checkbox/example/basic/component';
import CodeComponent
  from '../../packages/cf-component-code/example/basic/component';
import highlightedCodeComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-code/example/basic/component';
import CopyableComponent
  from '../../packages/cf-component-copyable-textarea/example/basic/component';
import highlightedCopyableComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-copyable-textarea/example/basic/component';
import DropdownComponent
  from '../../packages/cf-component-dropdown/example/basic/component';
import highlightedDropdownComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-dropdown/example/basic/component';
import DynamicComponent
  from '../../packages/cf-component-dynamic-content/example/basic/component';
import highlightedDynamicComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-dynamic-content/example/basic/component';
import FlexComponent
  from '../../packages/cf-component-flex/example/basic/component';
import highlightedFlexComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-flex/example/basic/component';
import FormComponent
  from '../../packages/cf-component-form/example/basic/component';
import highlightedFormComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-form/example/basic/component';
import HeadingComponent
  from '../../packages/cf-component-heading/example/basic/component';
import highlightedHeadingComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-heading/example/basic/component';
import IconComponent
  from '../../packages/cf-component-icon/example/basic/component';
import highlightedIconComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-icon/example/basic/component';
import InputComponent
  from '../../packages/cf-component-input/example/basic/component';
import highlightedInputComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-input/example/basic/component';
import LabelComponent
  from '../../packages/cf-component-label/example/basic/component';
import highlightedLabelComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-label/example/basic/component';
import LayoutComponent
  from '../../packages/cf-component-layout/example/basic/component';
import highlightedLayoutComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-layout/example/basic/component';
import LinkComponent
  from '../../packages/cf-component-link/example/basic/component';
import highlightedLinkComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-link/example/basic/component';
import ListComponent
  from '../../packages/cf-component-list/example/basic/component';
import highlightedListComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-list/example/basic/component';
import LoadingComponent
  from '../../packages/cf-component-loading/example/basic/component';
import highlightedLoadingComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-loading/example/basic/component';
import ModalComponent
  from '../../packages/cf-component-modal/example/basic/component';
import highlightedModalComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-modal/example/basic/component';
import NotificationsComponent
  from '../../packages/cf-component-notifications/example/basic/component';
import highlightedNotificationsComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-notifications/example/basic/component';
import PageComponent
  from '../../packages/cf-component-page/example/basic/component';
import highlightedPageComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-page/example/basic/component';
import PaginationComponent
  from '../../packages/cf-component-pagination/example/basic/component';
import highlightedPaginationComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-pagination/example/basic/component';
import ProgressComponent
  from '../../packages/cf-component-progress/example/basic/component';
import highlightedProgressComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-progress/example/basic/component';
import RadioComponent
  from '../../packages/cf-component-radio/example/basic/component';
import highlightedRadioComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-radio/example/basic/component';
import SelectComponent
  from '../../packages/cf-component-select/example/basic/component';
import highlightedSelectComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-select/example/basic/component';
import TableComponent
  from '../../packages/cf-component-table/example/basic/component';
import highlightedTableComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-table/example/basic/component';
import TabsComponent
  from '../../packages/cf-component-tabs/example/basic/component';
import highlightedTabsComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-tabs/example/basic/component';
import TextComponent
  from '../../packages/cf-component-text/example/basic/component';
import highlightedTextComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-text/example/basic/component';
import TextareaComponent
  from '../../packages/cf-component-textarea/example/basic/component';
import highlightedTextareaComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-textarea/example/basic/component';
import ToggleComponent
  from '../../packages/cf-component-toggle/example/basic/component';
import highlightedToggleComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-toggle/example/basic/component';
import TypographyComponent
  from '../../packages/cf-component-typography/example/basic/component';
import highlightedTypographyComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-typography/example/basic/component';
import ViewportComponent
  from '../../packages/cf-component-viewport/example/basic/component';
import highlightedViewportComponent
  from '!highlight-loader?raw=true&lang=jsx!../../packages/cf-component-viewport/example/basic/component';

const Examples = () => (
  <div className="cf-example-content">

    <h2 className="cf-example__heading" id="cf-builder-card">
      cf-builder-card
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-builder-card--basic">
        <CardBuilder />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedCardBuilder }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-builder-pagination">
      cf-builder-pagination
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-builder-pagination--basic">
        <PaginationBuilder />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedPaginationBuilder }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-builder-table">
      cf-builder-table
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-builder-table--basic">
        <TableBuilder />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedTableBuilder }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-button">
      cf-component-button
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-button--basic">
        <ButtonComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedButtonComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-callout">
      cf-component-callout
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-callout--basic">
        <CalloutComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedCalloutComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-card">
      cf-component-card
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-card--basic">
        <CardComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedCardComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-checkbox">
      cf-component-checkbox
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-checkbox--basic">
        <CheckboxComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedCheckboxComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-code">
      cf-component-code
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-code--basic">
        <CodeComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedCodeComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-copyable-textarea">
      cf-component-copyable-textarea
    </h2>
    <div className="cf-example">
      <div
        className="cf-example__content"
        id="cf-component-copyable-textarea--basic"
      >
        <CopyableComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedCopyableComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-dropdown">
      cf-component-dropdown
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-dropdown--basic">
        <DropdownComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedDropdownComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-dynamic-content">
      cf-component-dynamic-content
    </h2>
    <div className="cf-example">
      <div
        className="cf-example__content"
        id="cf-component-dynamic-content--basic"
      >
        <DynamicComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedDynamicComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-flex">
      cf-component-flex
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-flex--basic">
        <FlexComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedFlexComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-form">
      cf-component-form
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-form--basic">
        <FormComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedFormComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-heading">
      cf-component-heading
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-heading--basic">
        <HeadingComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedHeadingComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-icon">
      cf-component-icon
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-icon--basic">
        <IconComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedIconComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-input">
      cf-component-input
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-input--basic">
        <InputComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedInputComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-label">
      cf-component-label
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-label--basic">
        <LabelComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedLabelComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-layout">
      cf-component-layout
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-layout--basic">
        <LayoutComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedLayoutComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-link">
      cf-component-link
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-link--basic">
        <LinkComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedLinkComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-list">
      cf-component-list
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-list--basic">
        <ListComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedListComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-loading">
      cf-component-loading
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-loading--basic">
        <LoadingComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedLoadingComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-modal">
      cf-component-modal
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-modal--basic">
        <ModalComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedModalComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-notifications">
      cf-component-notifications
    </h2>
    <div className="cf-example">
      <div
        className="cf-example__content"
        id="cf-component-notifications--basic"
      >
        <NotificationsComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{
            __html: highlightedNotificationsComponent
          }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-page">
      cf-component-page
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-page--basic">
        <PageComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedPageComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-pagination">
      cf-component-pagination
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-pagination--basic">
        <PaginationComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedPaginationComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-progress">
      cf-component-progress
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-progress--basic">
        <ProgressComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedProgressComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-radio">
      cf-component-radio
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-radio--basic">
        <RadioComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedRadioComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-select">
      cf-component-select
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-select--basic">
        <SelectComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedSelectComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-table">
      cf-component-table
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-table--basic">
        <TableComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedTableComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-tabs">
      cf-component-tabs
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-tabs--basic">
        <TabsComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedTabsComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-text">
      cf-component-text
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-text--basic">
        <TextComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedTextComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-textarea">
      cf-component-textarea
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-textarea--basic">
        <TextareaComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedTextareaComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-toggle">
      cf-component-toggle
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-toggle--basic">
        <ToggleComponent />
      </div>
      <div className="cf-example__code">
        <pre dangerouslySetInnerHTML={{ __html: highlightedToggleComponent }} />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-typography">
      cf-component-typography
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-typography--basic">
        <TypographyComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedTypographyComponent }}
        />
      </div>
    </div>

    <h2 className="cf-example__heading" id="cf-component-viewport">
      cf-component-viewport
    </h2>
    <div className="cf-example">
      <div className="cf-example__content" id="cf-component-viewport--basic">
        <ViewportComponent />
      </div>
      <div className="cf-example__code">
        <pre
          dangerouslySetInnerHTML={{ __html: highlightedViewportComponent }}
        />
      </div>
    </div>

  </div>
);

export const packages = [
  'cf-builder-card',
  'cf-builder-pagination',
  'cf-builder-table',
  'cf-component-button',
  'cf-component-callout',
  'cf-component-card',
  'cf-component-checkbox',
  'cf-component-code',
  'cf-component-copyable-textarea',
  'cf-component-dropdown',
  'cf-component-dynamic-content',
  'cf-component-flex',
  'cf-component-form',
  'cf-component-heading',
  'cf-component-icon',
  'cf-component-input',
  'cf-component-label',
  'cf-component-layout',
  'cf-component-link',
  'cf-component-list',
  'cf-component-loading',
  'cf-component-modal',
  'cf-component-notifications',
  'cf-component-page',
  'cf-component-pagination',
  'cf-component-progress',
  'cf-component-radio',
  'cf-component-select',
  'cf-component-table',
  'cf-component-tabs',
  'cf-component-text',
  'cf-component-textarea',
  'cf-component-toggle',
  'cf-component-typography',
  'cf-component-viewport'
];
export default Examples;
