import React from 'react';
import { createStore, combineReducers } from 'redux';
import { Provider } from 'react-redux';
import Examples, { packages } from './examples';
import logo from '../assets/logo.png';

//  import reducers (can be autogenerated as well)
import cardReducer from '../../packages/cf-builder-card/src/cardReducer';
import tableReducer from '../../packages/cf-builder-table/src/tableReducer';

const reducer = combineReducers({
  cards: cardReducer,
  tables: tableReducer
});

const store = createStore(reducer);

const Main = () => (
  <div>
    <header className="cf-example-header">
      <a href="https://github.com/cloudflare/cf-ui">
        <img src={logo} alt="cf-ui" height="50" />
      </a>
    </header>
    <nav className="cf-example-sidebar">
      <a href="#cf-component-button">
        cf-component-button
      </a>
    </nav>
    <Provider store={store}>
      <Examples />
    </Provider>
  </div>
);

Main.displayName = 'Main';
export default Main;
