import React from 'react';
import { createStore, combineReducers } from 'redux';
import { Provider } from 'react-redux';
import { ThemeProvider } from 'cf-style-container';
import { variables } from 'cf-style-const';
import Examples, { packages } from './examples';
import logo from '../assets/logo.png';

import '../assets/base.css';
import '../assets/styles.css';

//  import reducers (can be autogenerated as well)
import cardReducer from '../../packages/cf-builder-card/src/cardReducer';
import tableReducer from '../../packages/cf-builder-table/src/tableReducer';

const reducer = combineReducers({
  cards: cardReducer,
  tables: tableReducer
});

const store = createStore(reducer);

const Main = () => (
  <ThemeProvider theme={variables}>
    <div>
      <header className="cf-example-header">
        <a href="https://github.com/cloudflare/cf-ui">
          <img src={logo} alt="cf-ui" height="50" />
        </a>
      </header>
      <nav className="cf-example-sidebar">
        {packages.map(pack => (
          <a key={pack} href={`#${pack}`}>
            {pack}
          </a>
        ))}
      </nav>
      <Provider store={store}>
        <Examples />
      </Provider>
    </div>
  </ThemeProvider>
);

Main.displayName = 'Main';
export default Main;
