parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - "cflint"
  - "react"
extends:
  - "plugin:react/recommended"
rules:
  # Possible Errors
  quotes:
    - 2
    - "single"
  # Best Practices
  block-scoped-var: 2
  default-case: 2
  guard-for-in: 2
  no-else-return: 2
  no-floating-decimal: 2
  no-self-compare: 2
  no-void: 2
  radix: 2
  ## Possible that this will switch to a "2" later
  wrap-iife: 2
  # Variables
  no-catch-shadow: 2
  # Node.js
  handle-callback-err: 2
  # Stylistic Issues
  brace-style:
    - 1
    - "1tbs"
  camelcase: 0
  comma-style:
    - 2
    - "last"
  comma-dangle:
    - 2
    - "never"
  no-lonely-if: 2
  no-nested-ternary: 2
  no-underscore-dangle: 0
  quote-props:
    - 1
    - "as-needed"
    - keywords: true
  semi:
    - 2
    - "always"
  space-unary-ops: 2
  no-unused-vars:
    - 2
    - vars: "all"
      args: "after-used"
  no-undef: 2
  react/displayName: 0
