const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

const ignoredPackages = [
  'cf-component-tooltip' // because it doesn't support server-side rendering
];

function capitalize(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

const packages = fs
  .readdirSync(path.resolve(__dirname, '../packages'))
  .filter(
    file =>
      file.indexOf('cf-builder-') === 0 || file.indexOf('cf-component-') === 0
  )
  .filter(file => !ignoredPackages.some(ignored => ignored === file));

console.log(packages);

const imports = packages.reduce(
  (acc, folder) => {
    const parts = folder.split('-');
    const name = capitalize(parts[2]) + capitalize(parts[1]);
    const hlName = `highlighted${name}`;
    return `${acc}
      import ${name} from '../../packages/${folder}/example/basic/component';
      import ${hlName} from '!highlight-loader?raw=true&lang=jsx!../../packages/${folder}/example/basic/component';`;
  },
  ''
);

const content = packages.reduce(
  (acc, folder) => {
    const parts = folder.split('-');
    const name = capitalize(parts[2]) + capitalize(parts[1]);
    const hlName = `highlighted${name}`;
    return `${acc}
      <h2 className="cf-example__heading" id="${folder}">
        ${folder}
      </h2>
      <div className="cf-example">
        <div className="cf-example__content" id="${folder}--basic">
          <${name} />
        </div>
        <div className="cf-example__code">
          <pre dangerouslySetInnerHTML={{ __html: ${hlName} }} />
        </div>
      </div>
    `;
  },
  ''
);

const examplePage = `
  /* THIS FILE IS AUTOGENERATED BY "npm run gen", DON'T TOUCH IT! */

  import React from 'react';
  ${imports}

  const Examples = () => (
    <div className="cf-example-content">
      ${content}
    </div>
  );

  export const packages = ['${packages.join("','")}'];
  export default Examples;
`;

const formattedExamplePage = prettier.format(examplePage, {
  singleQuote: true
});

const output = path.resolve(__dirname, './components/examples.js');
fs.writeFile(output, formattedExamplePage, err => {
  if (err) throw err;
  console.log(`${output} has been autogenerated!`);
});
