// flow-typed signature: ab272bf6f08b34ba7b6a097cbb632437
// flow-typed version: <<STUB>>/array.prototype.find_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array.prototype.find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'array.prototype.find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array.prototype.find/implementation' {
  declare module.exports: any;
}

declare module 'array.prototype.find/polyfill' {
  declare module.exports: any;
}

declare module 'array.prototype.find/shim' {
  declare module.exports: any;
}

declare module 'array.prototype.find/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array.prototype.find/implementation.js' {
  declare module.exports: $Exports<'array.prototype.find/implementation'>;
}
declare module 'array.prototype.find/index' {
  declare module.exports: $Exports<'array.prototype.find'>;
}
declare module 'array.prototype.find/index.js' {
  declare module.exports: $Exports<'array.prototype.find'>;
}
declare module 'array.prototype.find/polyfill.js' {
  declare module.exports: $Exports<'array.prototype.find/polyfill'>;
}
declare module 'array.prototype.find/shim.js' {
  declare module.exports: $Exports<'array.prototype.find/shim'>;
}
declare module 'array.prototype.find/tests/test.js' {
  declare module.exports: $Exports<'array.prototype.find/tests/test'>;
}
