// flow-typed signature: a289dd1311d6d62d1bc9482832c842ea
// flow-typed version: <<STUB>>/array-includes_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-includes' {
  declare module.exports: any;
}
