// flow-typed signature: 6e80cabc859676fced7050cefd67b50b
// flow-typed version: <<STUB>>/exenv_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exenv' {
  declare module.exports: any;
}
