// flow-typed signature: ecc73d2dfb51e683493d2917a7ff92c1
// flow-typed version: <<STUB>>/object-assign_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object-assign/index' {
  declare module.exports: $Exports<'object-assign'>;
}
declare module 'object-assign/index.js' {
  declare module.exports: $Exports<'object-assign'>;
}
