// flow-typed signature: ba1ff730a015a773f84e80f34247a9fb
// flow-typed version: <<STUB>>/object-is_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-is' {
  declare module.exports: any;
}
