// flow-typed signature: f8e2a6ee6c5eb316603933815f787450
// flow-typed version: <<STUB>>/raf_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf' {
  declare module.exports: any;
}
