// flow-typed signature: 1bd4a1ce77d3f6fa9d23f9e54388c944
// flow-typed version: <<STUB>>/react-gateway_v2.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-gateway'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-gateway' {
  declare module.exports: any;
}
