// flow-typed signature: fa3d278b59f079facc2d0cadb43e3a48
// flow-typed version: <<STUB>>/react-select_v0.9/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}
