// flow-typed signature: 68ebe169921fabc807b388356d70ef7f
// flow-typed version: <<STUB>>/react-addons-css-transition-group_v15.4.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-css-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-css-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-css-transition-group/index' {
  declare module.exports: $Exports<'react-addons-css-transition-group'>;
}
declare module 'react-addons-css-transition-group/index.js' {
  declare module.exports: $Exports<'react-addons-css-transition-group'>;
}
