// flow-typed signature: e3a4eec11e820f0c80351680463f31ac
// flow-typed version: <<STUB>>/react-modal2_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-modal2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-modal2' {
  declare module.exports: any;
}
