// flow-typed signature: f0546b8e8a9196b88c439305f3b24ff3
// flow-typed version: <<STUB>>/redux-mock-store_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-mock-store' {
  declare module.exports: any;
}
