// flow-typed signature: dd30cd6b459c8a93fbffc21deb56e899
// flow-typed version: <<STUB>>/string.prototype.trimleft_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.trimleft'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.trimleft' {
  declare module.exports: any;
}
