// flow-typed signature: f64c8f9716dfea08030e63bfec122a7d
// flow-typed version: <<STUB>>/string.prototype.startswith_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.startswith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.startswith' {
  declare module.exports: any;
}
