// flow-typed signature: 46c8414980be6e511269cf68db1d0c48
// flow-typed version: <<STUB>>/string.prototype.endswith_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.endswith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.endswith' {
  declare module.exports: any;
}
