// flow-typed signature: 6e8e1cff885deb3823ad8359dbe5291d
// flow-typed version: <<STUB>>/string.prototype.trim_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.trim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.trim' {
  declare module.exports: any;
}
