// flow-typed signature: 769ecd15183daf115d25a982e9c200db
// flow-typed version: <<STUB>>/string.prototype.trimright_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.prototype.trimright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.prototype.trimright' {
  declare module.exports: any;
}
