// flow-typed signature: b378dc28d875e215c24e4d2675dcdf7a
// flow-typed version: <<STUB>>/string-includes_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-includes' {
  declare module.exports: any;
}
