// flow-typed signature: 0150c3a1924a8595b28873af9fc5de4a
// flow-typed version: <<STUB>>/tether-tooltip_vx.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tether-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tether-tooltip' {
  declare module.exports: any;
}
