# -*- mode: Yaml -*- vim: set ft=yaml:
---
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: true
    experimentalObjectRestSpread: true
env:
  node: true
  es6: true
  mocha: true
rules:
  no-unused-expressions: 0
  new-cap: 0
