export default {
  font: 'inherit',
  fontWeight: 700,
  border: 'none',
  borderRadius: '3px',
  paddingTop: '.5em',
  paddingRight: '.1em',
  paddingBottom: '.5em',
  paddingLeft: '.1em',
  marginTop: 0,
  marginRight: '.2em',
  marginBottom: '.2em',
  marginLeft: 0,
  cursor: 'pointer',
  color: '#fff',
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: 'rgba(0, 0, 0, .2)',
  borderBottomWidth: '3px',
  boxShadow: '0 1px 2px rgba(0, 0, 0, .1)',
  backgroundDefault: 'gray',
  backgroundPrimary: '#00a9eb',
  backgroundSuccess: '#68970f',
  backgroundWarning: '#fca520',
  backgroundDanger: '#ff3100'
};
