export default {
  fontSize: '15px',
  inputFontSize: '13px',
  lineHeight: 1.5,
  inputLineHeight: 1.4,
  em: '1em',
  rem: '1rem',
  fontFamily: 'inherit',
  weightLight: 300,
  weightNormal: 400,
  weightSemiBold: 600,
  weightBold: 700,
  fontWeight: 400,
  borderRadius: '2px',
  arrowSize: '5px',
  colorWhite: 'white',
  colorOffsetLight: '+15%',
  colorOffsetDark: '-7%',
  defaultBackground: 'gray',
  primaryBackground: '#00a9eb',
  successBackground: '#68970f',
  warningBackground: '#fca520',
  dangerBackground: '#ff3100',
  disabledBackground: '#ededed'
};
